include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/*.config.dart"
  errors:
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
    inference_failure_on_function_invocation: ignore
